themes/osi/inc/template-functions.php
themes/osi/template-parts/content-page.php
themes/osi/template-parts/header-featured-image.php

* Added the creation and last modified dates to the page header
* Keep the dates at the bottom of the page is the page isn't using a header
* Open an old page (created before Feb 2023) from the Frontend
* Confirm that the Created and Last modified dates appear in the header, just below the title.
* Edit the page and change its template to "No page header"
* Open it from the Frontend and confirm that the page dates appear at the bottom of the page.
**Page with header**
**Page without header**
Mentions #9

Add last modified date in the header

---

themes/osi/templates/template-no-header-title.php

* Created the "No Header with Title" template
* Edit a page and assign it the "No Header with Title" template to it
* Assign a featured image to the page
* Open the page from the Frontend and confirm that the featured image isn't being displayed in the header 
* Confirm that the title (h1) is also rendered before the page content
Mentions #19

Added "No Header with title" template

---

themes/osi/footer.php
themes/osi/functions.php

* Added the "Footer - Above credits" sidebar
* Removed the max-width restriction from the footer
* Go to Appearance > Widgets and confirm that there's a sidebar named "Footer - Above credits"
* Add content there
* Open any page from the Frontend and confirm that this content gets rendered in the footer, above the colophon credits
* Confirm that the content of the footer is taking the 100% of its width.
Mentions #21

Added a footer sidebar and removed max-width limitation (dev)

---

themes/osi/inc/sugar-calendar.php

- https://github.com/OpenSourceOrg/dotOrg/pull/36
- When setting the ticket price, if the price is `0`, it should be set to `0.0` else the weird characters appear
- This is the default functionality of the `Sugar Calendar` plugin `Util` functions
- Replace $0.0 Per Ticket with Free Event
- Replace `Get a Ticket` button text with `Register`

Fix : Free Tickets [ PROD ]

---

themes/osi/inc/sugar-calendar.php

- https://github.com/OpenSourceOrg/dotOrg/pull/37
- Redirect `/events` to `/events/?event-display=upcoming`
- The order of events will be in ascending order i.e. closest event (date-wise) first.
- Only applicable for the archive page along with no `GET['event-display']` parameter

Fix : Set Upcoming Events as Default [ PROD ]

---

.gitignore
mu-plugins/websub-compat.php

Still send pings for the old `blog.opensource.org` Feed-URLs.
* The PR adds the `blog.opensource.org` Feed URLs to the list of updated Feed URLs, to keep backwards compatibility.
*
Mentions #

Add: WebSub backwards compatibility for the blog subdomain

---

.gitignore
mu-plugins/activitypub-migration.php

This adds the fields that are required for the ActivityPub target domain.
* https://docs.joinmastodon.org/user/moving/
* https://blog.joinmastodon.org/2019/06/how-to-migrate-from-one-server-to-another/

Add Actor migration

---

plugins/osi-features/inc/classes/post-types/class-base.php

- Add rewrite slug to custom post types so CPTs don't pick up the `/blog/` permalink added to blog posts.
1. Save permalinks
2. CPTs should not have `/blog/` added to URLs

Add rewrite slug to custom post types

---

plugins/osi-features/inc/classes/post-types/class-post-type-press-mentions.php

- Add rewrite slug to press mentions so CPTs don't pick up the `/blog/` permalink added to blog posts.
1. Save permalinks
2. Press mentions should not have `/blog/` added to URLs

Fix rewrite URL for press mentions

---

themes/osi/archive-sc_event.php
themes/osi/functions.php
themes/osi/inc/sugar-calendar.php
themes/osi/template-parts/content-press-mentions.php
themes/osi/template-parts/content.php

* Adding conditionals to code to protect against Sugar Calendar plugin deactivation
* Shouldn't get fatals when Sugar Calendar is deactivated, but everything should still work if it is. 
( dev request 3895 )

Protecting against Sugar Calendar deactivation

---

themes/osi/archive-sc_event.php
themes/osi/functions.php
themes/osi/inc/sugar-calendar.php
themes/osi/template-parts/content-press-mentions.php
themes/osi/template-parts/content.php

Third try for autodeployment

---

mu-plugins/osi-events-manager-tweaks/osi-events-manager-tweaks.php

* Display "Free" instead of 0.00$
* Open an event page (like [this](https://open-source-initiative-development.mystagingwebsite.com/events/open-source-ai-definition-town-hall-may-31)) and confirm that if the event is free, "Free" is displayed instead of "$0.00"
Mentions https://github.com/a8cteam51/opensource-net/issues/49

Display "Free" instead of 0.00$ (dev)

---

themes/osi/template-parts/header-featured-image.php

* Disable header for posts/events without featured image
* Open an event page from the Frontend (like [this one](https://open-source-initiative-development.mystagingwebsite.com/events/open-source-ai-definition-town-hall-2024-06-14))
* Confirm that if the event has a featured image, it gets rendered in the header
* Confirm that if the event doesn't have any featured image, no blank space is rendered in the header
Mentions [#](https://github.com/a8cteam51/opensource-net/issues/50)

Disable header for posts/events without featured image (dev)

---

themes/osi/page.php
themes/osi/template-parts/breadcrumbs-sc_event.php

* Add breadcrumbs to the single Event page
* Open a single event page from the Frontend
* Confirm that it has breadcrumbs, linking to the Home, the Events page and mentioning the current event.
Mentions https://github.com/a8cteam51/opensource-net/issues/50

Add breadcrumbs to the single Event page (dev)

---

themes/osi/index.php
themes/osi/page.php
themes/osi/single.php
themes/osi/template-parts/breadcrumbs-sc_event.php
themes/osi/template-parts/header-featured-image.php

* Disable header for posts/events without featured image 
* Add breadcrumbs to the single Event page
* Open an event page from the Frontend (like [this one](https://open-source-initiative-development.mystagingwebsite.com/events/open-source-ai-definition-town-hall-2024-06-14))
* Confirm that if the event has a featured image, it gets rendered in the header
* Confirm that if the event doesn't have any featured image, no blank space is rendered in the header
* Open a single event page from the Frontend
* Confirm that it has breadcrumbs, linking to the Home, the Events page and mentioning the current event.
Mentions https://github.com/a8cteam51/opensource-net/issues/50

Event page updates

---

themes/osi/inc/template-tags.php

* Don't display the updated date for blog posts (and archive) but the published date
* The blog posts and blog archive should display the published date
Mentions #93

Don't display the updated date for blog posts but published date

---

themes/osi/inc/template-tags.php

* Exclude meeting minutes post type for displaying updated time
*
Mentions #93

Exclude meeting minutes post type for displaying updated time

---

themes/osi/template-parts/content.php

* Always display comment block
* Comments are on discourse, we need to display the board link even if no comments have been posted.
*
Mentions #

Always display comment block

---

themes/osi/inc/template-functions.php

- `Non-OSI` (`Open Source Initiative`) events to open in a `new tab`.
- Add a hook to the `the_content` filter and determine if an `event` is `Non-OSI`
- `Non-OSI` event is determined by checking whether event allows `Bookings/Registrations`
- All the links in the content that don't point to `opensource.org` are modified with `target="_blank"` attribute.

Feature : Non-OSI content links open in a new tab

---

themes/osi/inc/template-functions.php

- `Non-OSI` (`Open Source Initiative`) events to open in a `new tab`.
- Add a hook to the `the_content` filter and determine if an `event` is `Non-OSI`
- `Non-OSI` event is determined by checking whether event allows `Bookings/Registrations`
- All the links in the content that don't point to `opensource.org` are modified with `target="_blank"` attribute.

Feature : Non-OSI content links open in a new tab [PROD]

---

.gitignore
plugins/osi-features/inc/classes/taxonomies/class-taxonomy-license-category.php
plugins/osi-features/inc/classes/taxonomies/class-taxonomy-publication.php
plugins/osi-features/inc/classes/taxonomies/class-taxonomy-seat-type.php
plugins/osi-features/inc/classes/taxonomies/class-taxonomy-status.php
plugins/osi-features/inc/classes/taxonomies/class-taxonomy-steward.php

* The Custom Post Type taxonomies were using the custom permalink (`/blog/%postname%`) when being viewed. This PR forces the removal of the pre-pended `/blog/` to the permalinks.
* Changes the "Status" taxonomy slug from `/status/` to `/about/board-of-directors/`.
* **_Use caution with_** page and status taxonomy naming since we already have a page/child-page structure being used. Child pages of `/about/board-of-directors/` may cause unpredictable results.
* Make sure to first "Save permalinks".
* View any of the taxonomies associated with any Custom Post Type. The `\blog\` in the permalink should not be present.
Mentions #115 , [4702](https://github.com/a8cteam51/team51-dev-requests/issues/4702)

Remove 'blog' from CPT taxonomies - develop

---

themes/osi/functions.php

_**Part of work by Team51**_
* Trim the Discourse comment body to 50 words
SEE DEV VERSION INTO STAGING https://github.com/OpenSourceOrg/dotOrg/pull/138
* Discourse comment body should have a maximum length of 50 words
Mentions #

Add filter to reduce the Discourse comment body to 50 words

---

themes/osi/functions.php

…1 of blog list
* Ensures that only the blog list page will limit page 0 to 1 less post. Allowing board of directors to list all!
* Shows the 12th item (max of 20!)
* Shows 11 on page 1 of the latest blogs
Mentions #144

Only limit the number of posts to account for the sticky blog on page

---

themes/osi/functions.php

* This PR includes functionality to create a new "Supporter" post when entries originally marked as spam in Flamingo, are marked as unspam.
Mentions #166

Send supporter form unspams to supporter CPT - develop

---

themes/osi/templates/template-no-header-title.php

* Add template support for the rest of the cpt
* Edit a podcast episode from the backend
* Click the template option in the sidebar and confirm that the `No Header with Title` template is available
* Assign this template to the episode and confirm it is rendered as expected.
Mentions #174

Add template support for the rest of the cpt (dev)

---

themes/osi/functions.php

* Added a custom permalink slug for podcasts 
* Go to Settings > Permalinks and confirm that the current structure is set to `/blog/%postname%`
* Open a podcast post from the frontend (following the link from the backend)
* Confirm that its URL is using a different permalink slug (`ai/podcast-post-name`)
* If you're getting a 404, flush the permalinks in Settings > General
Mentions #174

Custom permalink slug for podcasts (dev)

---

plugins/osi-features/inc/classes/class-plugin.php
plugins/osi-features/inc/classes/post-types/class-post-type-press-mentions.php

* This is an attempt to help with posting Press mentions automatically from a Google sheet via 3rd party automators such as Make or Zapier. At the moment, these services don't recognize the custom fields created by ACF. This change is an attempt to fix or rule out ACF as the cause of the issue.
Mentions #116

Move ACF fields to OSI plugin - Develop

---

themes/osi/template-parts/breadcrumbs.php

* Included podcasts to breadcrumbs 
* Open any podcast post from the frontend
* Confirm that the breadcrumbs are rendered in the page with the following format:
`Home / Podcast / current podcast name`
* Confirm that all the links are correct
Mentions #174

Included podcasts to breadcrumbs

---

themes/osi/inc/template-tags.php

Fix issues with incorrect type

---

.gitignore
mu-plugins/osi-api/osi-api.php
mu-plugins/osi-sponsors-list/osi-sponsors-list.php

* Creates 2 endpoints
* /license/{slug} > single license
* /licenses/?name={name like}&keywords={cat serach}&stewards={steward term search}
> calling `/licenses` will show all
I have also added a set of redirects, so we can access these using 
https://opensoure.org/api/license/blue-oak-model-license/ 
or
https://opensoure.org/api/licenses?name=MIT
If we want to handle this from api.opensoure.org/licenses?name=MIT we can look at doing redirects from server level before WP/PHP kicks in. 
Calling https://opensource.gq/wp-json/osi/v1/licenses?name=MIT
https://opensource.gq/wp-json/osi/v1/licenses?steward=boost
https://opensource.gq/wp-json/osi/v1/licenses?keyword=international
Mentions #199

Feature/gh199 license api  dev
